name: NPM Publish

on:
  release:
    types: [published]

jobs:
  analyze:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/code-analysis.yaml@master
    with:
      ref: ${{ github.ref }}
      default_branch: ${{ github.event.repository.default_branch }}
      push_before_sha: ${{ github.event.before }}
      push_base_sha: ${{ github.event.base_ref }}
      pull_base_sha: ${{ github.event.pull_request.base.sha }}
      gitguardian_api_key_ref: op://devops/GitGuardian/credential
    secrets: inherit

  publish:
    name: Publish
    needs: [analyze]
    uses: cabrera-evil/workflows/.github/workflows/publish-npm.yaml@master
    with:
      npm_token_ref: op://devops/NPM/credential
    secrets: inherit
