name: NPM Publish
description: |
  This workflow is triggered when a new release is published. It runs code analysis and dependency analysis, and if everything is fine, it publishes the package to npm.

on:
  release:
    types: [published]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  analyze_code:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/code-analysis.yaml@master
    with:
      default_branch: ${{ github.event.repository.default_branch }}
      push_before_sha: ${{ github.event.before }}
      push_base_sha: ${{ github.event.base_ref }}
    secrets: inherit

  analyze_deps:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/deps-analysis.yaml@master
    with:
      report: true
    secrets: inherit

  publish:
    name: Publish
    needs: [analyze_code, analyze_deps]
    uses: cabrera-evil/workflows/.github/workflows/publish-npm.yaml@master
    secrets: inherit
